language:
  python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install nose
  - pip install mypy-lang
  - pip install flake8
  - pip install -r requirements.txt

script:
  - flake8
  - mypy --silent-imports opwen_email_server
  - nosetests
