language: python

python:
  - "3.6"

sudo: required

services:
  - docker

cache: pip

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - docker-ce

script: travis/ci.sh

before_deploy:
  - openssl aes-256-cbc -K $encrypted_785169cb9db6_key -iv $encrypted_785169cb9db6_iv -in travis/secrets.tar.enc -out travis/secrets.tar -d
  - tar xvf travis/secrets.tar -C secrets

deploy:
  - provider: script
    script: travis/cd.sh
    on:
      repo: ascoderu/opwen-cloudserver
      tags: true
