language: python

python:
  - "3.6"

sudo: required

services:
  - docker

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

script: travis/ci.sh

before_deploy:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

deploy:
  - provider: script
    script: travis/cd.sh
    on:
      repo: ascoderu/opwen-cloudserver
      tags: true
