version: '3'

services:

  nginx:
    image: cwolff/opwenserver_nginx:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "${APP_PORT}:80"
    links:
      - api:frontend
    depends_on:
      - api

  api:
    image: cwolff/opwenserver_api:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      - GUNICORN_WORKERS=3
      - API_NAME=opwen_email_server/static/email-api-spec.yaml
    env_file:
      - ${ENV_FILE}

  job_send_outbound_emails:
    image: cwolff/opwenserver_send_outbound_emails:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/job/Dockerfile
    environment:
      - JOB_NAME=send_outbound_emails
    env_file:
      - ${ENV_FILE}

  job_store_inbound_emails:
    image: cwolff/opwenserver_store_inbound_emails:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/job/Dockerfile
    environment:
      - JOB_NAME=store_inbound_emails
    env_file:
      - ${ENV_FILE}

  job_store_written_client_emails:
    image: cwolff/opwenserver_store_written_client_emails:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/job/Dockerfile
    environment:
      - JOB_NAME=store_written_client_emails
    env_file:
      - ${ENV_FILE}
