version: '3'

services:

  nginx:
    image: cwolff/opwenserver_nginx:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - ${APP_PORT}:80
    links:
      - api_email_receive:api_email_receive
      - api_client_write:api_client_write
      - api_client_read:api_client_read
    depends_on:
      - api_email_receive
      - api_client_write
      - api_client_read

  api_email_receive:
    image: cwolff/opwenserver_api:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      - GUNICORN_WORKERS=${EMAIL_RECEIVE_API_WORKERS}
      - API_NAME=opwen_email_server/static/email-receive-spec.yaml
    env_file:
      - ${ENV_FILE}

  api_client_write:
    image: cwolff/opwenserver_api:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      - GUNICORN_WORKERS=${CLIENT_WRITE_API_WORKERS}
      - API_NAME=opwen_email_server/static/client-write-spec.yaml
    env_file:
      - ${ENV_FILE}

  api_client_read:
    image: cwolff/opwenserver_api:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      - GUNICORN_WORKERS=${CLIENT_READ_API_WORKERS}
      - API_NAME=opwen_email_server/static/client-read-spec.yaml
    env_file:
      - ${ENV_FILE}

  job_send_outbound_emails:
    image: cwolff/opwenserver_job:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/job/Dockerfile
    environment:
      - JOB_NAME=opwen_email_server.jobs.send_outbound_emails
    env_file:
      - ${ENV_FILE}

  job_store_inbound_emails:
    image: cwolff/opwenserver_job:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/job/Dockerfile
    environment:
      - JOB_NAME=opwen_email_server.jobs.store_inbound_emails
    env_file:
      - ${ENV_FILE}

  job_store_written_client_emails:
    image: cwolff/opwenserver_job:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/job/Dockerfile
    environment:
      - JOB_NAME=opwen_email_server.jobs.store_written_client_emails
    env_file:
      - ${ENV_FILE}
