version: '3'

services:

  api_email_receive:
    image: cwolff/opwenserver_api_email_receive:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/api/Dockerfile
      args:
        - API_NAME=opwen_email_server/static/email-receive-spec.yaml
    ports:
      - ${API_RECEIVE_PORT}:80
    environment:
      - GUNICORN_WORKERS=5
    env_file:
      - ${ENV_FILE}

  api_client_write:
    image: cwolff/opwenserver_api_client_write:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/api/Dockerfile
      args:
        - API_NAME=opwen_email_server/static/client-write-spec.yaml
    ports:
      - ${API_WRITE_PORT}:80
    environment:
      - GUNICORN_WORKERS=3
    env_file:
      - ${ENV_FILE}

  api_client_read:
    image: cwolff/opwenserver_api_client_read:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/api/Dockerfile
      args:
        - API_NAME=opwen_email_server/static/client-read-spec.yaml
    ports:
      - ${API_READ_PORT}:80
    environment:
      - GUNICORN_WORKERS=3
    env_file:
      - ${ENV_FILE}

  job_send_outbound_emails:
    image: cwolff/opwenserver_send_outbound_emails:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/job/Dockerfile
    environment:
      - JOB_NAME=send_outbound_emails
    env_file:
      - ${ENV_FILE}

  job_store_inbound_emails:
    image: cwolff/opwenserver_store_inbound_emails:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/job/Dockerfile
    environment:
      - JOB_NAME=store_inbound_emails
    env_file:
      - ${ENV_FILE}

  job_store_written_client_emails:
    image: cwolff/opwenserver_store_written_client_emails:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/job/Dockerfile
    environment:
      - JOB_NAME=store_written_client_emails
    env_file:
      - ${ENV_FILE}
