version: '3'

services:

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    links:
      - api:frontend
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    env_file:
      - .env

  send_outbound_emails:
    build:
      context: .
      dockerfile: docker/job/Dockerfile
    environment:
      - JOB_NAME=send_outbound_emails
    env_file:
      - .env

  store_inbound_emails:
    build:
      context: .
      dockerfile: docker/job/Dockerfile
    environment:
      - JOB_NAME=store_inbound_emails
    env_file:
      - .env

  store_writte_client_emails:
    build:
      context: .
      dockerfile: docker/job/Dockerfile
    environment:
      - JOB_NAME=store_written_client_emails
    env_file:
      - .env
