apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: nginx
spec:
  maxReplicas: {{.Values.autoscale.maxPods}}
  minReplicas: {{.Values.autoscale.minPods}}
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: nginx
  targetCPUUtilizationPercentage: {{.Values.autoscale.cpuThreshold}}
